/**
 * Authentic NCERT-aligned micro-topics for every Class 9 chapter.
 * Key format: "SubjectName:Chapter Title"
 * Each array has 10–14 granular sub-topics drawn from the actual NCERT
 * chapter structure (sections, exercises, and key concepts).
 */

export const CLASS9_MICRO_TOPICS: Record<string, string[]> = {

  // ══════════════════════════════════════════════════════
  //  MATHEMATICS  (16 chapters)
  // ══════════════════════════════════════════════════════

  "Mathematics:Orienting Yourself: The Use of Coordinates": [
    "Cartesian Plane — Axes, Quadrants & Origin",
    "Plotting Points on the Cartesian Plane",
    "Reading Coordinates from a Graph",
    "Identifying Quadrants of Given Points",
    "Distance of a Point from the Axes",
    "Real-World Coordinate Mapping (Maps & Grids)",
    "Mirror Images Across Axes",
    "NCERT Exercise 3.1 — Plotting & Reading",
    "Previous Year MCQs on Coordinates",
    "Self-Assessment — Coordinate Geometry Basics",
  ],

  "Mathematics:Introduction to Linear Polynomials": [
    "Polynomials — Definition, Degree & Types",
    "Zeros of a Polynomial — Concept & Meaning",
    "Linear Polynomial and Its Zero",
    "Remainder Theorem — Statement & Proof",
    "Factor Theorem — Statement & Application",
    "Factorising a Polynomial Using the Factor Theorem",
    "Algebraic Identities Used in Factorisation",
    "NCERT Exercise 2.1–2.3 Walkthrough",
    "Graphical Meaning of Zeros of a Polynomial",
    "Common Errors in Polynomial Division",
    "Previous Year Questions on Polynomials",
    "Practice Set — Remainder & Factor Theorem",
  ],

  "Mathematics:The World of Numbers": [
    "Number System Hierarchy — Natural, Whole, Integer, Rational",
    "Irrational Numbers — Definition & Examples (√2, π)",
    "Real Numbers on the Number Line",
    "Representing Irrational Numbers on the Number Line",
    "Operations on Real Numbers",
    "Rationalisation of Denominators",
    "Laws of Exponents for Real Numbers",
    "Decimal Expansion — Terminating vs Non-Terminating",
    "NCERT Exercise 1.1–1.5 Walkthrough",
    "Previous Year Questions on Number Systems",
    "HOTS — Proving Irrationality of Numbers",
    "Practice Set — Number Line & Rationalisation",
  ],

  "Mathematics:Exploring Algebraic Identities": [
    "Standard Algebraic Identities — (a+b)², (a-b)², (a+b)(a-b)",
    "Identity (a+b+c)² — Expansion & Verification",
    "Cubic Identities — (a+b)³ and (a-b)³",
    "Sum/Difference of Cubes — a³+b³ and a³-b³",
    "Applying Identities to Factorise Expressions",
    "Verification of Identities by Substitution",
    "Using Identities for Mental Math & Estimation",
    "NCERT Exercise 2.4–2.5 Walkthrough",
    "Worked Examples — Factorisation Using Identities",
    "Common Errors & Misconceptions",
    "Previous Year Questions on Algebraic Identities",
    "Practice Set — Identities & Factorisation",
  ],

  "Mathematics:I'm Up and Down, and Round and Round": [
    "Introduction to Periodic / Cyclic Phenomena",
    "Angle Measurement — Degrees vs Radians (Intro)",
    "Unit Circle — Centre, Radius & Points",
    "Sine and Cosine as Coordinates on the Unit Circle",
    "Graphs of sin x and cos x — Shape & Periodicity",
    "Amplitude, Period & Key Values (0°, 90°, 180°, 270°, 360°)",
    "Real-World Applications of Circular Motion",
    "NCERT Activity — Tracing Sinusoidal Motion",
    "Introduction to tan x and Its Behaviour",
    "Previous Year Questions on Circular Concepts",
    "Practice Set — Periodic Graphs & Key Angles",
  ],

  "Mathematics:Measuring Space: Perimeter and Area": [
    "Revision — Perimeter of Triangles, Quadrilaterals & Circles",
    "Heron's Formula — Derivation & Application",
    "Area of a Triangle — Using Base & Height vs Heron's",
    "Area of Quadrilaterals by Dividing into Triangles",
    "Area of a Trapezium — Formula & Examples",
    "Combining Shapes — Area of Composite Figures",
    "NCERT Exercise 10.1 — Heron's Formula Problems",
    "Real-World Area Problems (Plots, Tiles, Fields)",
    "Previous Year Questions on Mensuration (Part 1)",
    "Common Errors in Area Calculation",
    "Self-Assessment — Heron's Formula & Composites",
  ],

  "Mathematics:The Mathematics of Maybe: Introduction to Probability": [
    "Probability — Intuitive Idea & Need",
    "Experiment, Event, Sample Space — Definitions",
    "Empirical (Experimental) Probability",
    "Probability of an Event from Frequency Data",
    "Complement of an Event — P(not A) = 1 – P(A)",
    "Impossible & Certain Events",
    "Equally Likely Outcomes",
    "NCERT Exercise 15.1 — Experimental Probability",
    "Real-Life Examples — Coin Toss, Dice, Spinner",
    "Previous Year Questions on Probability",
    "HOTS — Probability from Tables & Graphs",
    "Practice Set — Experimental Probability",
  ],

  "Mathematics:Predicting What Comes Next: Exploring Sequences and Progressions": [
    "Patterns & Sequences — Introduction",
    "Arithmetic Progression (AP) — Definition & Notation",
    "Common Difference & General Term (aₙ = a + (n−1)d)",
    "Finding the nth Term of an AP",
    "Sum of First n Terms of an AP — Formula & Derivation",
    "Geometric Progression (GP) — Introduction & Common Ratio",
    "nth Term of a GP",
    "Identifying AP vs GP from Given Sequences",
    "Word Problems on AP (Savings, Seats, etc.)",
    "NCERT Exercise Walkthrough",
    "Previous Year Questions on Sequences",
    "HOTS — Mixed AP/GP Sequence Problems",
  ],

  "Mathematics:Introduction to Euclid's Geometry": [
    "Euclid's Definitions — Point, Line, Plane",
    "Euclid's Axioms — All Five Stated & Explained",
    "Euclid's Postulates — Especially the Parallel Postulate",
    "Theorems vs Axioms — Difference & Role",
    "Proof of Theorem 5.1 — Two Lines Cut by Transversal",
    "Non-Euclidean Geometry — Brief Concept",
    "NCERT Exercise 5.1 Questions Discussed",
    "Historical Context of Euclid & Greek Geometry",
    "Previous Year Questions on Euclid's Geometry",
    "Self-Assessment — Axioms, Postulates & Proofs",
  ],

  "Mathematics:Lines and Angles": [
    "Basic Terms — Line, Line Segment, Ray, Angle Types",
    "Pairs of Angles — Complementary, Supplementary, Adjacent, Linear Pair",
    "Vertically Opposite Angles — Theorem & Proof",
    "Transversal Crossing Parallel Lines — All Angle Pairs",
    "Corresponding, Alternate & Co-Interior Angles",
    "Conditions for Lines to Be Parallel",
    "Angle Sum Property of a Triangle — Proof",
    "Exterior Angle Theorem",
    "NCERT Exercise 6.1–6.3 Walkthrough",
    "Previous Year Questions on Lines & Angles",
    "HOTS — Multi-step Angle Proofs",
    "Practice Set — Parallel Lines & Angles",
  ],

  "Mathematics:Triangles": [
    "Congruence of Triangles — Meaning & Notation",
    "Criteria for Congruence — SAS, ASA, AAS, SSS, RHS",
    "Proving Congruence — Step-by-Step Examples",
    "Properties of Isosceles Triangle — Theorem & Converse",
    "Inequalities in Triangles — Longer Side vs Larger Angle",
    "Triangle Inequality Theorem",
    "Angle Sum Property Revisited with Proof",
    "NCERT Exercise 7.1–7.4 Walkthrough",
    "Previous Year Proof Questions on Triangles",
    "HOTS — Multi-step Triangle Congruence Proofs",
    "Common Errors in Congruence Notation",
    "Practice Set — Congruence & Triangle Properties",
  ],

  "Mathematics:Quadrilaterals": [
    "Angle Sum Property of a Quadrilateral",
    "Types of Quadrilaterals — Parallelogram, Rhombus, Rectangle, Square, Trapezium",
    "Properties of a Parallelogram — Theorems 1–5",
    "Conditions for a Quadrilateral to Be a Parallelogram",
    "Mid-Point Theorem — Statement & Proof",
    "Converse of Mid-Point Theorem",
    "NCERT Exercise 8.1–8.2 Walkthrough",
    "Diagonal Properties of Special Quadrilaterals",
    "Previous Year Questions on Quadrilaterals",
    "HOTS — Proofs Using Mid-Point Theorem",
    "Quick Revision — Comparison Table of Quadrilateral Types",
    "Practice Set — Parallelogram & Mid-Point Theorem",
  ],

  "Mathematics:Circles": [
    "Circle Terminology — Centre, Radius, Chord, Arc, Sector, Segment",
    "Equal Chords and Their Distances from Centre — Theorem",
    "Perpendicular from Centre to a Chord — Theorem & Proof",
    "Angle Subtended by a Chord at the Centre & Circumference",
    "Angle in a Semicircle is 90° — Theorem & Proof",
    "Angles in the Same Segment are Equal — Theorem",
    "Cyclic Quadrilateral — Opposite Angles Sum = 180°",
    "Tangent to a Circle — Perpendicularity Theorem (Intro)",
    "NCERT Exercise 10.1–10.2 Walkthrough",
    "Previous Year Questions on Circles",
    "HOTS — Multi-theorem Circle Proofs",
    "Practice Set — Circle Theorems",
  ],

  "Mathematics:Linear Equations in Two Variables": [
    "Linear Equation in Two Variables — ax + by + c = 0",
    "Solutions of a Linear Equation — Infinitely Many",
    "Graphical Representation — Line on Cartesian Plane",
    "Equations of Lines Parallel to Axes (x = a, y = b)",
    "Graph of y = mx — Lines Through Origin",
    "NCERT Exercise 4.1–4.3 Walkthrough",
    "Real-World Modelling with Two-Variable Equations",
    "Checking Whether a Point Lies on a Line",
    "Previous Year Questions on Linear Equations",
    "Common Errors in Plotting & Verifying Solutions",
    "Practice Set — Equations & Graphs",
  ],

  "Mathematics:Mensuration": [
    "Surface Area of a Cuboid — Formula & Derivation",
    "Surface Area of a Cube",
    "Surface Area of a Right Circular Cylinder — Curved & Total",
    "Surface Area of a Right Circular Cone — Slant Height",
    "Surface Area of a Sphere & Hemisphere",
    "Volume of a Cuboid & Cube",
    "Volume of a Cylinder",
    "Volume of a Cone",
    "Volume of a Sphere & Hemisphere",
    "Conversion of Units — cm³ to litres, etc.",
    "NCERT Exercise 13.1–13.9 Walkthrough",
    "Real-World Problems (Tanks, Cones, Pipes)",
    "Previous Year Questions on Surface Area & Volume",
    "Practice Set — Mixed Mensuration Problems",
  ],

  "Mathematics:Statistics": [
    "Data — Primary vs Secondary, Raw vs Grouped",
    "Frequency Distribution Table — Construction",
    "Bar Graphs — Drawing & Interpretation",
    "Histograms — Construction & Reading",
    "Frequency Polygons",
    "Measures of Central Tendency — Mean, Median, Mode",
    "Mean of Ungrouped Data — Direct Method",
    "Median of Ungrouped Data — Steps",
    "Mode of Ungrouped Data",
    "NCERT Exercise 14.1–14.4 Walkthrough",
    "Real-Life Data Interpretation Problems",
    "Previous Year Questions on Statistics",
    "HOTS — Drawing Conclusions from Data",
    "Practice Set — Central Tendency & Graphs",
  ],

  // ══════════════════════════════════════════════════════
  //  SCIENCE  (13 chapters)
  // ══════════════════════════════════════════════════════

  "Science:Entering the World of Secondary Science": [
    "What is Science? — Branches & Scientific Method",
    "Observation, Hypothesis, Experiment & Conclusion",
    "Safety in the Science Lab — Rules & Equipment",
    "Measurement — SI Units & Significant Figures",
    "Scientific Notation & Order of Magnitude",
    "Sources of Information in Science",
    "Technology vs Science — Relationship & Differences",
    "Environment & Sustainability — Overview",
    "NCERT Activity-Based Questions",
    "Self-Assessment — Intro to Secondary Science",
  ],

  "Science:Cell: The Unit of Life": [
    "Cell Theory — Schleiden, Schwann & Virchow",
    "Prokaryotic vs Eukaryotic Cells — Differences",
    "Cell Size, Shape & Diversity",
    "Cell Wall vs Cell Membrane — Structure & Function",
    "Nucleus — Structure (Nuclear Envelope, Nucleolus, Chromatin)",
    "Cytoplasm & Cytosol",
    "Mitochondria — Structure & Function (Powerhouse)",
    "Plastids — Chloroplasts, Leucoplasts, Chromoplasts",
    "Vacuoles, Lysosomes & Golgi Apparatus",
    "Endoplasmic Reticulum — Rough vs Smooth",
    "Centrosome & Centrioles",
    "NCERT Exercise & Diagram-Based Questions",
    "Previous Year Questions on Cell Biology",
    "Practice Set — Cell Organelles & Functions",
  ],

  "Science:Tissues": [
    "Meristematic Tissues — Apical, Lateral, Intercalary",
    "Permanent Tissues — Simple: Parenchyma, Collenchyma, Sclerenchyma",
    "Complex Tissues — Xylem (Vessels, Tracheids, Fibres, Parenchyma)",
    "Phloem — Sieve Tubes, Companion Cells, Fibres, Parenchyma",
    "Epidermis & Stomata — Guard Cells & Function",
    "Animal Tissues Overview — Epithelial, Connective, Muscular, Neural",
    "Epithelial Tissue — Squamous, Cuboidal, Columnar, Ciliated",
    "Connective Tissue — Blood, Bone, Cartilage, Tendons, Ligaments",
    "Muscular Tissue — Striated, Smooth, Cardiac",
    "Nervous Tissue — Neurons & Neuroglia",
    "Labelled Diagrams — Plant and Animal Tissue Types",
    "NCERT Exercise Walkthrough",
    "Previous Year Questions on Tissues",
    "Practice Set — Plant vs Animal Tissues",
  ],

  "Science:Diversity in Living Organisms": [
    "Basis of Classification — Evolution & Hierarchy",
    "Five-Kingdom Classification — Monera, Protista, Fungi, Plantae, Animalia",
    "Kingdom Monera — Bacteria (Structure, Types, Importance)",
    "Kingdom Protista — Amoeba, Paramecium, Euglena",
    "Kingdom Fungi — Bread Mould, Yeast, Mushrooms",
    "Kingdom Plantae — Thallophyta, Bryophyta, Pteridophyta",
    "Gymnosperms & Angiosperms — Differences",
    "Kingdom Animalia — Porifera, Coelenterata, Platyhelminthes",
    "Nematoda, Annelida, Arthropoda, Mollusca, Echinodermata",
    "Vertebrates — Fish, Amphibia, Reptilia, Aves, Mammalia",
    "NCERT Exercise Walkthrough & Classification Table",
    "Previous Year Questions on Classification",
    "HOTS — Reasons for Classification Decisions",
    "Practice Set — Five Kingdoms & Animal Phyla",
  ],

  "Science:Exploring Mixtures and Their Separation": [
    "Pure Substances vs Mixtures — Definitions & Examples",
    "Homogeneous vs Heterogeneous Mixtures",
    "Solutions — Solute, Solvent, Solubility",
    "Concentration of a Solution — % by Mass/Volume",
    "Saturated vs Unsaturated Solutions",
    "Colloids vs Suspensions — Tyndall Effect",
    "Separation Methods — Evaporation, Distillation, Crystallisation",
    "Chromatography — Paper Chromatography Activity",
    "Centrifugation — Principle & Application",
    "Fractional Distillation — Crude Oil Refining",
    "Separating Immiscible Liquids — Separating Funnel",
    "NCERT Activity-Based Questions",
    "Previous Year Questions on Mixtures",
    "Practice Set — Separation Techniques",
  ],

  "Science:Atoms and Molecules": [
    "Laws of Chemical Combination — Conservation of Mass",
    "Law of Definite Proportions & Multiple Proportions",
    "Dalton's Atomic Theory — Postulates & Limitations",
    "Atoms — Symbol, Mass, Atomicity",
    "Molecules of Elements vs Compounds",
    "Ions — Cations and Anions with Examples",
    "Chemical Formulae — Writing & Interpreting",
    "Molecular Mass & Formula Unit Mass",
    "Mole Concept — Definition & Significance",
    "Avogadro's Number (6.022 × 10²³)",
    "Molar Mass & Calculations",
    "NCERT Exercise 3.1–3.3 Walkthrough",
    "Previous Year Questions on Atoms & Moles",
    "Practice Set — Mole Concept Numericals",
  ],

  "Science:Structure of the Atom": [
    "Thomson's Model of the Atom — Plum Pudding",
    "Rutherford's Alpha-Scattering Experiment — Setup & Observations",
    "Rutherford's Nuclear Model — Nucleus, Electrons",
    "Limitations of Rutherford's Model",
    "Bohr's Model — Postulates, Shells (K, L, M, N)",
    "Valence Electrons & Valence Shell",
    "Atomic Number & Mass Number",
    "Isotopes — Examples (Hydrogen, Carbon, Chlorine)",
    "Isobars — Examples & Significance",
    "Electronic Configuration — First 20 Elements",
    "Distribution of Electrons in Shells (2, 8, 8 Rule)",
    "NCERT Exercise Walkthrough",
    "Previous Year Questions on Atomic Structure",
    "Practice Set — Electronic Configuration & Isotopes",
  ],

  "Science:Earth as a System: Matter, Energy and Life": [
    "Earth as a System — Four Spheres (Lithosphere, Hydrosphere, Atmosphere, Biosphere)",
    "Matter & Energy Flow Between Spheres",
    "Atmosphere — Composition & Layers",
    "Nitrogen Cycle — Processes & Organisms Involved",
    "Carbon Cycle — Role of Photosynthesis & Respiration",
    "Oxygen Cycle",
    "Water Cycle — Evaporation, Condensation, Precipitation",
    "Biogeochemical Cycles — Significance for Life",
    "Greenhouse Effect & Global Warming — Brief Intro",
    "NCERT Activity-Based Questions",
    "Previous Year Questions on Earth Systems",
    "Practice Set — Cycles & Earth's Spheres",
  ],

  "Science:Describing Motion Around Us": [
    "Motion vs Rest — Relative Nature of Motion",
    "Distance vs Displacement — Scalar vs Vector",
    "Uniform vs Non-Uniform Motion",
    "Speed, Velocity & Average Speed/Velocity",
    "Acceleration — Positive, Negative, Zero",
    "Equations of Motion — v = u + at, s = ut + ½at², v² = u² + 2as",
    "Derivation of Equations of Motion (Graphical & Algebraic)",
    "Distance–Time Graphs — Interpreting Slopes",
    "Velocity–Time Graphs — Interpreting Area & Slope",
    "Uniform Circular Motion — Definition & Centripetal Acceleration",
    "NCERT Exercise 8.1–8.3 Walkthrough",
    "Numerical Problems on Equations of Motion",
    "Previous Year Questions on Motion",
    "Practice Set — Graphs & Equations of Motion",
  ],

  "Science:Force and Laws of Motion": [
    "Force — Contact vs Non-Contact; Balanced vs Unbalanced",
    "Newton's First Law — Inertia, Mass & Inertia of Rest/Motion",
    "Momentum — Definition (p = mv) & Significance",
    "Newton's Second Law — F = ma (Derivation from Momentum)",
    "Newton's Third Law — Action & Reaction with Examples",
    "Conservation of Linear Momentum",
    "Applications — Recoil of a Gun, Rocket Propulsion",
    "Numerical Problems on Newton's Laws",
    "NCERT Exercise 9.1–9.3 Walkthrough",
    "Previous Year Questions on Laws of Motion",
    "HOTS — Multi-Force Scenarios",
    "Practice Set — Momentum & Newton's Laws",
  ],

  "Science:Work, Energy and Simple Machines": [
    "Work — Definition, Conditions & W = Fs cos θ",
    "Positive, Negative & Zero Work with Examples",
    "Energy — Kinetic Energy (KE = ½mv²) Derivation",
    "Potential Energy — Gravitational (PE = mgh) Derivation",
    "Law of Conservation of Energy",
    "Work-Energy Theorem",
    "Power — Definition, Unit (Watt) & P = W/t",
    "Commercial Unit of Energy — kWh (kilowatt-hour)",
    "Simple Machines — Lever, Pulley, Inclined Plane, Screw",
    "Mechanical Advantage, Velocity Ratio & Efficiency",
    "NCERT Exercise 11.1–11.3 Walkthrough",
    "Numerical Problems on Work & Power",
    "Previous Year Questions on Work & Energy",
    "Practice Set — Energy Conservation & Machines",
  ],

  "Science:Sound": [
    "Production & Propagation of Sound",
    "Sound Needs a Medium — Vacuum Experiment",
    "Longitudinal Waves — Compressions & Rarefactions",
    "Frequency, Wavelength, Amplitude & Time Period",
    "Speed of Sound — Factors Affecting, Value in Air",
    "Reflection of Sound — Echo & Reverberation",
    "Applications of Reflection — SONAR, Megaphone",
    "Range of Hearing — Infrasonic, Audible, Ultrasonic",
    "Uses of Ultrasound — Medical Imaging, SONAR",
    "NCERT Exercise 12.1–12.3 Walkthrough",
    "Numerical Problems on Speed of Sound & Echo",
    "Previous Year Questions on Sound",
    "HOTS — Sound in Different Media",
    "Practice Set — Waves, Echo & Ultrasound",
  ],

  "Science:Our Environment": [
    "Components of Ecosystem — Biotic & Abiotic",
    "Food Chain & Food Web — Construction & Examples",
    "Trophic Levels & Energy Flow (10% Rule)",
    "Biodegradable vs Non-Biodegradable Waste",
    "Ozone Layer — Formation & Depletion (CFCs)",
    "Garbage Management — Reduce, Reuse, Recycle",
    "Effect of Human Activities on the Environment",
    "Sustainable Development — Concept",
    "NCERT Exercise 15.1 Walkthrough",
    "Previous Year Questions on Environment",
    "Value-Based Questions — Individual Responsibility",
    "Practice Set — Food Webs & Environmental Impact",
  ],

  // ══════════════════════════════════════════════════════
  //  SOCIAL SCIENCE  (16 chapters)
  // ══════════════════════════════════════════════════════

  "Social Science:Understanding History and Past": [
    "What is History? — Meaning and Scope",
    "Sources of History — Primary and Secondary",
    "Archaeological Sources — Coins, Inscriptions, Monuments",
    "Literary Sources — Chronicles, Travelogues, Religious Texts",
    "Periodisation of Indian History — Ancient, Medieval, Modern",
    "Timeline Construction — Key Epochs in World History",
    "History vs Myth vs Legend",
    "Historical Thinking — Causation, Change & Continuity",
    "NCERT Exercise Questions",
    "Previous Year Questions on Historical Methodology",
  ],

  "Social Science:Early Humans and Beginning of Civilisation": [
    "Palaeolithic Period — Hunter-Gatherer Life & Tools",
    "Mesolithic Period — Microlithic Tools & Lifestyle",
    "Neolithic Revolution — Agriculture, Animal Domestication",
    "Chalcolithic Age — Copper Tools & Early Farming Villages",
    "Iron Age — Introduction & Impact",
    "Indus Valley Civilisation — Sites & Urban Features",
    "Town Planning in Harappa & Mohenjo-Daro",
    "Decline of the Indus Valley Civilisation — Theories",
    "Vedic Period — Early and Later Vedic Culture",
    "NCERT Exercise Questions",
    "Map Work — Ancient Civilisation Sites",
    "Previous Year Questions on Early Civilisations",
  ],

  "Social Science:State and Society (upto 1000 CE)": [
    "Mauryan Empire — Chandragupta, Bindusara & Ashoka",
    "Ashoka's Dhamma — Principles & Inscriptions",
    "Decline of the Mauryan Empire",
    "Post-Mauryan Period — Kushanas, Satavahanas",
    "Gupta Empire — Chandragupta I, II & Samudragupta",
    "Gupta Age as Golden Age — Art, Science & Literature",
    "Religion & Society — Buddhism, Jainism, Brahminism",
    "Emergence of Feudalism in India",
    "South Indian Kingdoms — Pallavas, Chalukyas, Cholas",
    "NCERT Exercise Questions",
    "Map Work — Ancient Indian Empires",
    "Previous Year Questions on Ancient India",
  ],

  "Social Science:Resistance and Resilience (1000 - 1700 CE)": [
    "Rajput Kingdoms — Rise & Decline",
    "Ghaznavid & Ghurid Invasions — Causes & Impact",
    "Delhi Sultanate — Slave Dynasty to Lodi Dynasty",
    "Alauddin Khalji's Reforms — Revenue, Market, Military",
    "Vijayanagara Empire — Administration & Culture",
    "Mughal Empire — Babur, Humayun, Akbar",
    "Akbar's Religious Policy — Sulh-i-Kul & Din-i-Ilahi",
    "Jahangir, Shah Jahan & Aurangzeb",
    "Maratha Rise Under Shivaji",
    "Bhakti & Sufi Movements — Saints & Significance",
    "NCERT Exercise Questions",
    "Map Work — Medieval India",
    "Previous Year Questions on Medieval India",
  ],

  "Social Science:India and the World - I (1900 BCE - 1200 CE)": [
    "Ancient Trade Routes — Silk Road & Maritime Routes",
    "India's Trade Contacts with West Asia & Rome",
    "Spread of Buddhism — Central Asia, China, Southeast Asia",
    "Indian Cultural Influence Abroad — Temples, Scripts, Art",
    "Arab Traders & Early Islamic Connections",
    "Chinese Travellers to India — Fa Hien, Hiuen Tsang",
    "Indian Mathematics & Science — Global Contributions",
    "Medieval Contact with Islamic World",
    "NCERT Exercise Questions",
    "Map Work — Ancient Trade Routes",
    "Previous Year Questions on India & World Connections",
  ],

  "Social Science:Shaping of the Earth's Surface": [
    "Earth's Interior — Crust, Mantle, Core (Outer & Inner)",
    "Plate Tectonics — Major & Minor Plates, Types of Boundaries",
    "Convergent, Divergent & Transform Plate Boundaries",
    "Earthquakes — Causes, Focus, Epicentre, Seismic Waves",
    "Richter Scale & Mercalli Scale",
    "Volcanoes — Types (Shield, Composite, Cinder) & Distribution",
    "Landforms Made by Internal Forces — Mountains, Plateaus, Plains",
    "Rocks — Igneous, Sedimentary, Metamorphic & Rock Cycle",
    "Weathering & Erosion — Agents & Landforms",
    "NCERT Exercise Questions",
    "Map Work — Tectonic Plates & Earthquake Zones",
    "Previous Year Questions on Interior of the Earth",
  ],

  "Social Science:Atmosphere and Climate": [
    "Atmosphere — Composition & Layers (Troposphere to Exosphere)",
    "Weather vs Climate — Definitions & Differences",
    "Elements of Weather — Temperature, Humidity, Precipitation, Wind",
    "Factors Affecting Climate — Latitude, Altitude, Ocean Currents",
    "Atmospheric Pressure & Wind Systems",
    "Monsoons — Mechanism Over the Indian Subcontinent",
    "Seasons in India — Southwest & Northeast Monsoon",
    "Clouds — Types and Rainfall Patterns",
    "Climate Change — Greenhouse Gases & Global Warming",
    "NCERT Exercise Questions",
    "Map Work — Wind Belts & Monsoon Patterns",
    "Previous Year Questions on Atmosphere & Climate",
  ],

  "Social Science:Oceans and Life": [
    "Oceans of the World — Names, Locations & Sizes",
    "Ocean Floor Features — Continental Shelf, Slope, Abyssal Plain",
    "Ocean Currents — Warm & Cold (Gulf Stream, Labrador)",
    "Effect of Ocean Currents on Climate",
    "Tides — Causes (Gravitational Pull of Moon & Sun), Types",
    "Marine Ecosystems — Coral Reefs, Mangroves",
    "Ocean Resources — Minerals, Fisheries, Energy",
    "Ocean Pollution — Plastics, Oil Spills & Impact",
    "Maritime Trade & Fishing Economy",
    "NCERT Exercise Questions",
    "Map Work — Ocean Currents & Maritime Routes",
    "Previous Year Questions on Oceans",
  ],

  "Social Science:Life on Earth": [
    "Biosphere — Definition & Extent",
    "Ecosystems — Components, Types (Forest, Grassland, Desert, Aquatic)",
    "Food Chains & Food Webs in Natural Ecosystems",
    "Biodiversity — Importance & Threats",
    "Conservation of Biodiversity — Protected Areas, National Parks",
    "Deforestation — Causes & Consequences",
    "Soil Degradation & Land Pollution",
    "Natural Vegetation Zones — Tropical, Temperate, Polar",
    "Wildlife & Endangered Species",
    "NCERT Exercise Questions",
    "Map Work — Biomes of the World",
    "Previous Year Questions on Biosphere & Environment",
  ],

  "Social Science:Democracy": [
    "What is Democracy? — Key Features & Definition",
    "Why Democracy? — Arguments For & Against",
    "Democracy vs Authoritarianism — Comparison",
    "Historical Development of Democracy — Athens & Modern Era",
    "Constitutional Democracy in India — Brief Overview",
    "Fundamental Rights as Basis of Democracy",
    "Role of Elections in a Democracy",
    "Challenges to Democracy — Corruption, Inequality",
    "NCERT Exercise Questions",
    "Previous Year Questions on Democracy",
  ],

  "Social Science:Elections": [
    "Why Elections? — Role in Democracy",
    "Types of Electoral Systems — FPTP, PR",
    "India's Electoral System — Lok Sabha & Vidhan Sabha",
    "Election Commission of India — Role & Powers",
    "Model Code of Conduct",
    "Nomination, Campaigning & Voting Process",
    "Role of Voters — Voter ID, Rights & Responsibilities",
    "Electronic Voting Machines (EVMs)",
    "Free & Fair Elections — Importance",
    "NCERT Exercise Questions",
    "Previous Year Questions on Elections in India",
  ],

  "Social Science:Authority": [
    "What is Authority? — Legitimate vs Illegitimate",
    "Sources of Authority — Traditional, Charismatic, Legal-Rational",
    "Political Authority — Government & State",
    "Constitution as Source of Authority in India",
    "Limits on Authority — Separation of Powers",
    "Rule of Law vs Arbitrary Rule",
    "Accountability — How Authority Is Checked",
    "Civil Society & Protest as Check on Authority",
    "NCERT Exercise Questions",
    "Previous Year Questions on Authority & Power",
  ],

  "Social Science:Building Blocks in Economics": [
    "Scarcity — The Basic Economic Problem",
    "Factors of Production — Land, Labour, Capital, Enterprise",
    "Goods & Services — Economic and Non-Economic",
    "Economic Sectors — Primary, Secondary, Tertiary",
    "Consumption, Production & Investment",
    "Market — Meaning & Types (Local, National, International)",
    "Price Mechanism — How Prices Signal Information",
    "India's GDP — Overview & Significance",
    "NCERT Exercise Questions",
    "Previous Year Questions on Basic Economics",
  ],

  "Social Science:The Price Puzzle: What Drives the Market": [
    "Demand — Meaning & Law of Demand",
    "Factors Affecting Demand (Income, Price of Related Goods)",
    "Supply — Meaning & Law of Supply",
    "Factors Affecting Supply",
    "Equilibrium Price — Where Demand Meets Supply",
    "Market Forces — How Prices Rise & Fall",
    "Price Controls — Ceiling & Floor Prices",
    "Inflation — Meaning, Causes & Impact on Common People",
    "Consumer Price Index (CPI) & Inflation Measurement",
    "NCERT Exercise Questions",
    "Previous Year Questions on Demand, Supply & Price",
  ],

  "Social Science:From Ideas to Startups": [
    "Entrepreneurship — Definition & Qualities of an Entrepreneur",
    "Idea Generation — Identifying Problems & Opportunities",
    "Business Plan — Components & Importance",
    "Types of Business Organisations — Sole Trader, Partnership, Company",
    "Startups vs Traditional Business — Key Differences",
    "Role of Innovation & Technology in Startups",
    "Funding a Startup — Bootstrapping, Angel Investors, Venture Capital",
    "Challenges Faced by Startups in India",
    "Government Initiatives — Startup India Scheme",
    "NCERT Exercise Questions",
    "Previous Year Questions on Entrepreneurship",
  ],

  "Social Science:Smart Ways to Manage Your Finances": [
    "Personal Finance — Income, Expenditure, Savings",
    "Budgeting — Making a Personal Budget",
    "Banking — Types of Accounts (Savings, Current, FD, RD)",
    "Interest — Simple & Compound Interest",
    "Insurance — Life, Health & Vehicle Insurance Basics",
    "Investment Options — PPF, Mutual Funds, Shares (Introduction)",
    "Taxation — Why We Pay Taxes; Direct & Indirect Taxes",
    "Digital Payments — UPI, Net Banking, Mobile Wallets",
    "Financial Literacy — Avoiding Debt Traps",
    "Consumer Rights in Financial Matters",
    "NCERT Exercise Questions",
    "Previous Year Questions on Financial Literacy",
  ],

  // ══════════════════════════════════════════════════════
  //  ENGLISH  (16 chapters — 8 prose + 8 poems)
  // ══════════════════════════════════════════════════════

  "English:How I Taught My Grandmother to Read": [
    "Author Introduction — Sudha Murty & Her Literary Style",
    "Summary — Part I (Setting & Characters)",
    "Summary — Part II (Conflict & Resolution)",
    "Theme — Education, Determination & Intergenerational Bond",
    "Character Analysis — The Grandmother",
    "Character Analysis — The Narrator/Child",
    "Values Portrayed — Respect for Elders, Love of Learning",
    "Word Meanings & Vocabulary Builder",
    "Short Answer Questions (2–3 marks)",
    "Long Answer Questions (5 marks)",
    "Extract-Based Questions Practice",
    "Grammar Link — Tense Usage in Narrative",
    "Self-Assessment — Chapter Quiz",
  ],

  "English:The Pot Maker": [
    "Author Introduction & Context",
    "Summary — Part I (The Potter's World)",
    "Summary — Part II (The Central Conflict)",
    "Theme — Livelihood, Craft & Tradition",
    "Character Study — The Potter",
    "Significance of the Title",
    "Social Message in the Story",
    "Word Meanings & Vocabulary",
    "Short Answer Questions",
    "Long Answer Questions",
    "Extract-Based Questions",
    "Grammar Link — Describing Processes",
    "Self-Assessment — Chapter Quiz",
  ],

  "English:Winds of Change": [
    "Author Introduction & Background",
    "Summary — Part I",
    "Summary — Part II",
    "Theme — Change, Courage & Adaptation",
    "Character Analysis — Protagonist",
    "Setting & Its Role in the Story",
    "Tone & Mood of the Narrative",
    "Word Meanings & Vocabulary",
    "Short Answer Questions",
    "Long Answer Questions",
    "Extract-Based Questions",
    "Value-Based Questions — Embracing Change",
    "Self-Assessment — Chapter Quiz",
  ],

  "English:Vitamin-M": [
    "Author Introduction",
    "Summary — The Story's Central Irony",
    "Theme — Money, Ambition & Reality",
    "Character Analysis — Main Character",
    "Humour & Satire in the Story",
    "Social Commentary on Economic Aspirations",
    "Word Meanings & Vocabulary",
    "Short Answer Questions",
    "Long Answer Questions",
    "Extract-Based Questions",
    "Value-Based Questions — True Success",
    "Grammar Link — Conditional Sentences",
    "Self-Assessment — Chapter Quiz",
  ],

  "English:The World of Limitless Possibilities": [
    "Author Introduction",
    "Summary — Part I (Vision & Opportunity)",
    "Summary — Part II (Overcoming Limits)",
    "Theme — Self-Belief, Technology & the Future",
    "Motivational Elements in the Text",
    "Real-World Connections — India's Progress",
    "Word Meanings & Vocabulary",
    "Short Answer Questions",
    "Long Answer Questions",
    "Extract-Based Questions",
    "Value-Based Questions — Growth Mindset",
    "Self-Assessment — Chapter Quiz",
  ],

  "English:Twin Melodies": [
    "Author Introduction",
    "Summary — The Story of Two Contrasting Lives",
    "Theme — Music, Identity & Destiny",
    "Character Comparison — The Two Protagonists",
    "Symbolism of Music in the Story",
    "Tone — Nostalgic and Lyrical",
    "Word Meanings & Vocabulary",
    "Short Answer Questions",
    "Long Answer Questions",
    "Extract-Based Questions",
    "Value-Based Questions — Power of Art",
    "Self-Assessment — Chapter Quiz",
  ],

  "English:Carrier of Words": [
    "Author Introduction",
    "Summary — Part I",
    "Summary — Part II",
    "Theme — Communication, Language & Human Connection",
    "Character Analysis",
    "Significance of the Title",
    "Word Meanings & Vocabulary",
    "Short Answer Questions",
    "Long Answer Questions",
    "Extract-Based Questions",
    "Grammar Link — Direct & Indirect Speech",
    "Self-Assessment — Chapter Quiz",
  ],

  "English:Follow That Dream": [
    "Author Introduction",
    "Summary — Part I (The Dream & the Journey)",
    "Summary — Part II (Obstacles & Triumph)",
    "Theme — Perseverance, Purpose & Success",
    "Character Study — The Dreamer",
    "Inspirational Message of the Story",
    "Word Meanings & Vocabulary",
    "Short Answer Questions",
    "Long Answer Questions",
    "Extract-Based Questions",
    "Value-Based Questions — Dream Big, Work Hard",
    "Self-Assessment — Chapter Quiz",
  ],

  "English:Bharat Our Land (poem)": [
    "Poet Introduction & Background",
    "Summary of the Poem",
    "Theme — Patriotism & National Pride",
    "Tone & Mood — Celebratory and Reverential",
    "Imagery & Poetic Devices Used",
    "Central Message of the Poet",
    "Word Meanings & Difficult Phrases",
    "Extract-Based Questions",
    "Short & Long Answer Questions",
    "Self-Assessment — Poem Quiz",
  ],

  "English:Gifts of Grace: Honouring Our Vocations (poem)": [
    "Poet Introduction",
    "Summary of the Poem",
    "Theme — Dignity of Labour & All Vocations",
    "Tone — Respectful and Grateful",
    "Poetic Devices — Metaphor, Personification",
    "Central Message",
    "Word Meanings",
    "Extract-Based Questions",
    "Short & Long Answer Questions",
    "Value-Based Questions — Respecting All Work",
    "Self-Assessment — Poem Quiz",
  ],

  "English:Canvas of Soil (poem)": [
    "Poet Introduction",
    "Summary of the Poem",
    "Theme — Nature, Agriculture & Rural India",
    "Imagery — Vivid Nature Descriptions",
    "Poetic Devices — Simile, Alliteration",
    "Tone — Earthy and Reverential",
    "Word Meanings",
    "Extract-Based Questions",
    "Short & Long Answer Questions",
    "Self-Assessment — Poem Quiz",
  ],

  "English:I Cannot Remember My Mother (poem)": [
    "Poet Introduction — Rabindranath Tagore",
    "Summary of the Poem",
    "Theme — Memory, Loss & Longing",
    "Tone — Melancholic and Tender",
    "Poetic Devices — Imagery, Symbolism",
    "Central Emotion & Its Universal Appeal",
    "Word Meanings",
    "Extract-Based Questions",
    "Short & Long Answer Questions",
    "Value-Based Questions — Cherishing Memories",
    "Self-Assessment — Poem Quiz",
  ],

  "English:Nine Gold Medals (poem)": [
    "Poet Introduction — David Roth",
    "Summary of the Poem",
    "Theme — Compassion, Sportsmanship & Human Spirit",
    "Story of the Special Olympics Race",
    "Tone — Uplifting and Emotional",
    "Poetic Devices Used",
    "Word Meanings",
    "Extract-Based Questions",
    "Short & Long Answer Questions",
    "Value-Based Questions — True Victory",
    "Self-Assessment — Poem Quiz",
  ],

  "English:A Friend Found in Music (poem)": [
    "Poet Introduction",
    "Summary of the Poem",
    "Theme — Music as a Universal Language & Friend",
    "Tone — Warm and Contemplative",
    "Poetic Devices — Personification, Metaphor",
    "Word Meanings",
    "Extract-Based Questions",
    "Short & Long Answer Questions",
    "Self-Assessment — Poem Quiz",
  ],

  "English:Words (poem)": [
    "Poet Introduction",
    "Summary of the Poem",
    "Theme — Power and Impact of Language",
    "Tone — Thoughtful and Cautionary",
    "Poetic Devices — Imagery, Metaphor",
    "Central Message — Words Heal or Hurt",
    "Word Meanings",
    "Extract-Based Questions",
    "Short & Long Answer Questions",
    "Value-Based Questions — Responsible Communication",
    "Self-Assessment — Poem Quiz",
  ],

  "English:Believe in Yourself (poem)": [
    "Poet Introduction",
    "Summary of the Poem",
    "Theme — Self-Confidence & Inner Strength",
    "Tone — Motivational and Empowering",
    "Poetic Devices — Anaphora, Repetition",
    "Word Meanings",
    "Extract-Based Questions",
    "Short & Long Answer Questions",
    "Value-Based Questions — Developing Self-Belief",
    "Self-Assessment — Poem Quiz",
  ],
};
